apiVersion: v1
kind: Pod
metadata:
  name: test-webserver2
spec:
  containers:
  - name: test-webserver2
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mydir
  volumes:
  - name: mydir
    hostPath:
      # Ensure the file directory is created.
      path: /var/local/data
      type: DirectoryOrCreate
  
