apiVersion: v1
kind: Service
metadata:
  name: green-nodesvc
  labels:
    app: nginx
    version: green
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31011
    protocol: TCP
  selector:
    app: nginx
    version: green
