apiVersion: v1
kind: Pod
metadata:
  name: secret-env1
spec:
  containers:
    - name: nginx
      image: nginx:1.9.1
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password
  restartPolicy: Never
